###

GET http://localhost:4000/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiSm9obiIsImlhdCI6MTYyNzYyODU5MiwiZXhwIjoxNjI3NjI4NjIyfQ.ZVnFWeGYBIPUL63TxZLSpSRQS3ekyv2xJj54M0Hbz3g

###

POST http://localhost:6000/login
Content-Type: application/json 

{
    "username": "John"
}
 
