###

GET http://localhost:3001/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiSm9obiIsImlhdCI6MTYyODI0MTQyMSwiZXhwIjoxNjI4MjQxNDUxfQ.eEnWDyqysteeUuMymaIfUjHgmVbiGjiqD8Iqqh5HlgQ

###

POST http://localhost:4000/login
Content-Type: application/json 

{
    "username": "John"
}
 
