const express = require('express');
const app = express();
const path = require('path');
const route = require('./routes/AuthLogin.route');
const POST = 4000;
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.urlencoded({ extended: true}));
app.use(express.json());
route(app);
app.listen(POST);