const express = require('express')
const app = express()
const path = require('path')
const route = require('./routes')
const mongodb = require('./config/database/mongodb')
const mysql = require('./config/database/mysql')
const POST = 8000
const jwt = require('jsonwebtoken')
const cors = require('cors')
app.use(cors()) 
app.use(express.static(path.join(__dirname, 'public')))
app.use(express.urlencoded({ extended: true}))
app.use(express.json())
route(app)
mongodb.connect()
mysql.connect()
app.listen(POST)