const express = require('express')
const app = express()
const path = require('path')
const route = require('./routes')
const db = require('./config/database')
const POST = 8000
const jwt = require('jsonwebtoken')
const dotenv = require('dotenv')
const cors = require('cors')
db.connect()
dotenv.config()
app.use(cors()) 
app.use(express.static(path.join(__dirname, 'public')))
app.use(express.urlencoded({ extended: true}))
app.use(express.json())
route(app)

app.listen(POST)